### ISSUE TITLE
Demo crashes when fetching tiles

### ISSUE THREAD

**Issue by DylanVanAssche** [openplannerteam/planner.js#124]
I wanted to try out `plannerjs`, so I installed it from NPM and used the demo code in the README:

```
const Planner = require('plannerjs').default;
const planner = new Planner.Planner();
planner.prefetchStops();
planner.prefetchConnections();

planner.query({
  from: "http://irail.be/stations/NMBS/008812005", // Brussels North
  to: "http://irail.be/stations/NMBS/008892007", // Ghent-Sint-Pieters
  minimumDepartureTime: new Date("Mon Sep 09 2019 16:00:00"),
  maximumArrivalTime: new Date("Mon Sep 09 2019 19:00:00"),
  publicTransportOnly: true,

  walkingSpeed: 3, // KmH
  minimumWalkingSpeed: 3, // KmH

  maximumWalkingDistance: 200, // meters

  minimumTransferDuration: Planner.Planner.Units.fromMinutes(1),
  maximumTransferDuration: Planner.Planner.Units.fromMinutes(30),

  maximumTravelDuration: Planner.Planner.Units.fromHours(1.5),

  maximumTransfers: 4,
})
  .take(3)
  .on('data', (path) => {
   console.log(path);
  })
  .on('end', () => {
    console.log('No more paths!')
  })
  .on('error', (error) => {
    console.error(error);
  });
```

However, this seems to crash when fetching some map tiles:

```
[dylan@desktop plannerjs-server]$ node index.js 
(node:21182) UnhandledPromiseRejectionWarning: FetchError: invalid response body at: https://tiles.openplanner.team/planet/14/8389/5494 reason: unexpected end of file
    at Gunzip.<anonymous> (/home/dylan/Projects/plannerjs-server/node_modules/node-fetch/lib/body.js:123:11)
    at Gunzip.emit (events.js:209:13)
    at Zlib.zlibOnError [as onerror] (zlib.js:173:8)
(node:21182) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:21182) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

This seems to go wrong while downloading and gunzipping the page. If you go to the webpage with a browser, the page is returned just fine.

**Comment by pietercolpaert** [comment]
We are fixing this by making sure the right configurations are available by default. We will release a new planner.js NPM package asap! Thanks for testing it!

**Comment by DylanVanAssche** [comment]
Thanks! Looking forward to it!

**Comment by pietercolpaert** [comment]
It’s released @DylanVanAssche

**Comment by DylanVanAssche** [comment]
Works great now!
Well, I would suggest to improve the example a little bit by making the results more readable:

```
Path {
  legs: [
    Leg { travelMode: 'train', steps: [Array] },
    Leg { travelMode: 'train', steps: [Array] }
  ]
}
No more paths!
``` 

After adding `JSON.stringify(path, null, 4)`:

```
{
    "legs": [
        {
            "travelMode": "train",
            "steps": [
                {
                    "duration": {
                        "average": 180000
                    },
                    "startLocation": {
                        "id": "http://irail.be/stations/NMBS/008812005",
                        "latitude": 50.859663,
                        "longitude": 4.360846,
                        "name": "Brussel-Noord/Bruxelles-Nord",
                        "avgStopTimes": 977190.476
                    },
                    "startTime": "2019-10-07T14:02:00.000Z",
                    "stopLocation": {
                        "id": "http://irail.be/stations/NMBS/008811007",
                        "latitude": 50.878513,
                        "longitude": 4.378636,
                        "name": "Schaarbeek/Schaerbeek",
                        "avgStopTimes": 738857.1429999999
                    },
                    "stopTime": "2019-10-07T14:05:00.000Z",
                    "enterConnectionId": "http://irail.be/connections/8812005/20191007/IC2014",
                    "exitConnectionId": "http://irail.be/connections/8812005/20191007/IC2014"
                }
            ]
        },
        {
            "travelMode": "train",
            "steps": [
                {
                    "duration": {
                        "average": 2820000
                    },
                    "startLocation": {
                        "id": "http://irail.be/stations/NMBS/008811007",
                        "latitude": 50.878513,
                        "longitude": 4.378636,
                        "name": "Schaarbeek/Schaerbeek",
                        "avgStopTimes": 738857.1429999999
                    },
                    "startTime": "2019-10-07T14:10:00.000Z",
                    "stopLocation": {
                        "id": "http://irail.be/stations/NMBS/008892007",
                        "latitude": 51.035896,
                        "longitude": 3.710675,
                        "name": "Gent-Sint-Pieters",
                        "avgStopTimes": 555968.254
                    },
                    "stopTime": "2019-10-07T14:57:00.000Z",
                    "enterConnectionId": "http://irail.be/connections/8811007/20191007/IC2837",
                    "exitConnectionId": "http://irail.be/connections/8814001/20191007/IC2837"
                }
            ]
        }
    ]
}
No more paths!
```
